server:
  port: 8081
spring:
  application:
    name: hmdp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    password: 1234
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
minio:
  endpoint: http://127.0.0.1:9000 #内网地址
  public: http://127.0.0.1:9000  #外网访问地址
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: dian-ping
  imagePath: image
  filePath: file
  videoPath: video
